### ISSUE TITLE
cuber does not sort input tif files

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos_cuber#3]
When named 0,1,2,3,4,... instead of 001,002, .... the order is messed up.

**Comment by jmrk84** [comment]
Suggested solution: Add something like this, and ask the user whether he wants to rename:

    import argparse
    import os
    import re
    import sys
    # public domain code from http://stackoverflow.com/questions/5417979/batch-rename-sequential-files-by-padding-with-zeroes
    def main(cmdline):

        parser = argparse.ArgumentParser(
            description='Ensure zero padding in numbering of files.')
        parser.add_argument('path', type=str,
            help='path to the directory containing the files')
    args = parser.parse_args()
    path = args.path

    numbered = re.compile(r'(.*?)(\d+)\.(.*)')

    numbered_fnames = [fname for fname in os.listdir(path)
                       if numbered.search(fname)]

    max_digits = max(len(numbered.search(fname).group(2))
                     for fname in numbered_fnames)

    for fname in numbered_fnames:
        _, prefix, num, ext, _  = numbered.split(fname, maxsplit=1)
        num = num.zfill(max_digits)
        new_fname = "{}{}.{}".format(prefix, num, ext)
        if fname != new_fname:
            os.rename(os.path.join(path, fname), os.path.join(path, new_fname))
            print "Renamed {} to {}".format(fname, new_fname)
        else:
            print "{} seems fine".format(fname)

    if __name__ == "__main__":
        sys.exit(main(sys.argv[1:]))

**Comment by mdraw** [comment]
I think we could solve this more elegantly by using a [natural sorting algorithm](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/) in [this line](https://github.com/knossos-project/knossos_cuber/blob/1ab5286ced35c0cbe6212e8829bdceece15db450/knossos_cuber/knossos_cuber.py#L667).
This way we wouldn't have to deal with renaming files and asking the user about that. Should I implement that?
