### ISSUE TITLE
converting 3D tif file to conf file

### ISSUE THREAD

**Issue by sunglyoungKim** [knossos-project/knossos_cuber#4]
Hello,

I am using ubuntu 18.04 and try to convert a 3D stacked tif file to conf file.

I have used the default config file but changed the boundary that fit into my image file.

The conversion works. However, the conf file is not in a stacked file or 3D file.

May I know what options should I give to get 3D stacked outcome?

Thank you

**Comment by Optiligence** [comment]
The knossos_cuber in it’s current state doesn’t support cubing 3d tiffs directly. 
Is it much effort for you to convert it to a stack of 2d tiffs first?

**Comment by sunglyoungKim** [comment]
Hello,

Thank you so much a quick response. 

So, basically, I need to convert from 3d tiffs to bunch of 2d tiffs files in the same directory. 

And run the cuber? 

I am usualy working in 3D dataset so I haven't used with a stack of 2d tiffs. However, I will try it

Thank you
